((nil . ((indent-tabs-mode . nil)
	 (tab-width . 8)
         ;;(coding . utf8)
	 (fill-column . 92)
	 (ispell-local-dictionary . "american")))
 (c-mode . ((c-file-style . "bsd")
	    (c-basic-offset . 4)))
 (sh-mode . ((sh-basic-offset . 4))))
