# See example script at https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

codecov: true

coveralls: true

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - export JULIA_LOAD_PATH='docs/:.:'
        - julia -e 'using Pkg;
                    Pkg.instantiate();
                    Pkg.add("Documenter")'
        - julia docs/make.jl
      after_success: skip
