# See example script at https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
  - osx

julia:
# - 0.6
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: 0.6
    - julia: 1.2
    - julia: nightly

notifications:
  email: false

before_script:
  - julia -e 'using Pkg;
              Pkg.add(PackageSpec(url="https://github.com/emmt/ArrayTools.jl"));'

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'using Pkg;
#              Pkg.add(PackageSpec(url="https://github.com/emmt/ArrayTools.jl"));
#              Pkg.add(PackageSpec(url="https://github.com/emmt/LazyAlgebra.jl"));
#              Pkg.build();
#              Pkg.test("LazyAlgebra"; coverage=true);';

after_success:
  - julia -e 'using Pkg end;
              cd(Pkg.dir("LazyAlgebra"));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(Coveralls.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.build("LazyAlgebra");
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
